# Generated by Django 4.1.1 on 2023-08-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeScreen', '0002_eğitimler_delete_urun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eğitimler',
            name='tarih',
            field=models.DateField(),
        ),
    ]
