# Generated by Django 4.1.1 on 2023-08-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeScreen', '0004_kadro'),
    ]

    operations = [
        migrations.AddField(
            model_name='kadro',
            name='linkedn',
            field=models.URLField(blank=True, null=True),
        ),
    ]
